name: open-machine-learning-jupyter-book
channels:
  - default
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - pip:
    - jupyter-book
    - sphinxcontrib-mermaid
    - sphinxcontrib-wavedrom
    - sphinxcontrib-plantuml
    - sphinxcontrib-tikz
    - sphinxcontrib-blockdiag
    - sphinxcontrib-drawio
    - git+https://github.com/bonartm/sphinxcontrib-quizdown.git