name: open-machine-learning-jupyter-book
channels:
  - conda-forge
dependencies:
  - python=3.9
  - sphinx
  - nbmake
  - pip
  - pip:
    - pytest
    - pandas
    - numpy
    - matplotlib
    - pywaffle
    - scikit-learn
    - scipy
    - seaborn
    - tensorflow
    - jupyter-book
    - notebook
    - jupyter_contrib_nbextensions
    - sphinxcontrib-mermaid
    - sphinxcontrib-wavedrom
    
